# Generated by Django 5.2.4 on 2025-07-16 14:23

from django.db import migrations

def combine_names(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Person = apps.get_model("persons", "Person")
    for person in Person.objects.all():
        person.name = f"{person.first_name} {person.last_name}"
        person.save()


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0002_person_first_name_person_last_name"),
    ]

    operations = [
        migrations.RunPython(combine_names),
    ]