# Generated by Django 5.2.4 on 2025-07-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_booleanfieldexample_charfieldexample_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DurationFieldExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='FilePathFieldExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FilePathField(path='/tmp')),
            ],
        ),
        migrations.CreateModel(
            name='IPAddressFieldExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='RegexFieldExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='datetimefieldexample',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
