# Generated by Django 5.2.4 on 2025-07-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_durationfieldexample_filepathfieldexample_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiddenfieldexample',
            name='user',
        ),
        migrations.AddField(
            model_name='hiddenfieldexample',
            name='modified',
            field=models.DateTimeField(default='1998-01-01 00:00:00'),
            preserve_default=False,
        ),
    ]
